"""The two call-graph rules: reachable complexity, and cycles between routines.

Every other structural rule in this package reads the **import** graph -- which file, class or
architecture node depends on which. This module reads the **call** graph: which routine calls
which. It is the one structural view an import graph cannot express, because a file's imports
say nothing about how much branching a reviewer inherits by calling one function in it.

:func:`evaluate_reachable_complexity` is the rule that serves "keep the complexity down"
directly. For each routine the run judges, it sums ``CyclomaticStrict`` over everything that
routine transitively calls, itself included. A three-line function that reaches a 400-branch
subtree is the thing that cannot be held in one head, and no per-entity threshold sees it: each
individual routine in that subtree is under its own limit.

:func:`find_call_cycles` is the call-graph analogue of ``structure.file_cycle``: a strongly
connected component of two or more routines is mutual recursion.

**Every finding here is a lower bound, and that is stated in the finding itself.**
:class:`~scitools_hook.models.snapshot.CallResolution` records the reason: Understand resolves
a Python call through an instance attribute to the *attribute*, not to the routine behind it.
Measured on Understand 6.5.1204 over 44 783 call sites of a 770-file Python project, 31.4% of
call sites bound to nothing callable at all; the same measurement over purpose-built C++
fixtures put it at 6.9% -- a small sample, 29 call sites, and the only claim held to the
installed Understand on every contract run is the ordering, that Python resolves a smaller
share than C++ does. So an edge this graph holds is real and a number this rule
reports is genuinely reached -- **exceeding a limit is a true positive** -- while staying under
one is not a clearance. Three things follow, and all three are enforced here rather than left
to the reader:

* A routine the graph does not hold is **not judged at all**. ``call_edges`` is bounded to the
  routines reachable from the ones the run asked about, so a missing node means "not looked
  at", never "reaches nothing" -- the question :attr:`ProjectSnapshot.call_graph_holds` exists
  to answer, and the first thing both rules ask.
* Every finding carries the resolution figure for its language and the number of call sites
  *inside its own reach* that bound to nothing. A reach of one is a different claim when the
  routine had no call sites and when it had forty that did not resolve.
* A reached routine written in a file that failed to parse is named in ``details``. Measured on
  the same project: three files with parse errors held 26, 18 and 24 routines in their source
  and Understand saw 12, 5 and 13 of them, so a reach that passes through such a file is
  missing nodes as well as edges.

**A total names the problem and not the work**, so a reach finding also ranks what it reached
by contribution: ``heaviest`` lists the reached routines carrying the most complexity, three of
them in the message and ten in the details. Without it the finding says "233 over 50 routines"
and hands the reader fifty unordered names.

As in the other structural evaluators, ``hint`` is left for the pipeline, ``limit_source`` is
``"rule"`` and ``blocking`` follows the configured severity (req 3.7). Both rules are ``>``
rules: a routine exactly at its limit is allowed. Whole-project mode needs no before side --
neither rule compares two sides, because a reach is a property of the code as it now stands.

Two measured notes on what these rules do *not* claim, both recorded because a reader would
otherwise assume the opposite:

* **Fan-in is deliberately not a rule here.** On the same project, the routine with the
  highest ``CyclomaticStrict`` of all -- a dataclass's ``__post_init__``, 45 -- has a call-graph
  fan-in of **zero**, because the call that runs it is generated by ``@dataclass`` and appears
  in no source file. A "nothing calls this" rule would have named it dead code, which is the
  opposite of the truth.
* **An entry point tops this rule by construction, and that is not a defect it found.** The
  highest reachable complexity in a program is, necessarily, at its ``main``: measured on the
  same project, the top of the non-test ranking is a golden-capture script's ``main`` at 1 474
  over 405 routines. The number is true and the routine is not the problem. What the rule is
  for is the *unexpected* one -- the small helper that pulls in a subtree nobody expected -- so
  an operator picks the limit from the distribution (measured over 3 187 non-test routines:
  p50 4, p90 33, p95 66, p99 189, max 1 474) and excludes entry points with the ``ignore``
  patterns that already exist, exactly as they would for any other rule.
* **Mutual recursion is rarer, and more often deliberate, than the file-level analogue.** The
  same 770 files hold exactly two routine cycles, both of them recursive descent over a nested
  structure, and 72 self-recursive routines that are not cycles at all. The rule is therefore
  worth running and worth defaulting to a warning; an operator who wants recursion banned can
  raise it, and one who does not can leave it.
"""

from __future__ import annotations

from collections.abc import Collection, Iterable, Mapping, Sequence
from dataclasses import dataclass
from typing import Final

from scitools_hook.analysis.structure.graph import (
    DependencyGraph,
    GraphEdge,
    strongly_connected_components,
)
from scitools_hook.config.models import Limit, Severity
from scitools_hook.models.findings import Finding, structure_rule
from scitools_hook.models.snapshot import (
    CallResolution,
    EntityKey,
    EntityRef,
    ProjectSnapshot,
)

REACH_RULE: Final = structure_rule("reachable_complexity")
CYCLE_RULE: Final = structure_rule("call_cycle")
COMPLEXITY_METRIC: Final = "CyclomaticStrict"
"""The metric a reach sums; named in messages so a reader knows what the number is."""

MESSAGE_CONTRIBUTORS: Final = 3
DETAIL_CONTRIBUTORS: Final = 10
"""How many of the heaviest reached routines the message and the details name.

Three in the line an operator reads and ten in the payload a tool reads: a message long enough
to scroll past is a message nobody reads, and a details list is not read by eye at all."""


@dataclass(frozen=True, slots=True)
class Reach:
    """Everything one routine transitively calls, with the confidence that answer carries."""

    subject: str
    """The routine's endpoint: its :attr:`~scitools_hook.models.snapshot.EntityKey.token`."""

    routines: tuple[str, ...]
    """Every reached endpoint including the subject, sorted; a self-call adds nothing."""

    complexity: float
    """Summed ``CyclomaticStrict`` over the reached routines the database could measure."""

    unmeasured: tuple[str, ...]
    """Reached routines the database has no ``CyclomaticStrict`` for; they add nothing."""

    unresolved_calls: int
    """Call sites inside the reached set that bound to nothing callable (the blind spot)."""

    truncated_by: tuple[str, ...]
    """Files of the reached set that failed to parse, so the reach is missing routines too."""


@dataclass(frozen=True, slots=True)
class CallGraph:
    """A snapshot's call graph, together with what it does and does not cover.

    Built once per run and shared by both rules, because both need the same three answers:
    which routines the graph holds, what each of them costs, and how much of the language's
    call graph resolved at all.
    """

    graph: DependencyGraph
    complexity: Mapping[str, float | None]
    unresolved: Mapping[str, int]
    resolution: Mapping[str, CallResolution]
    held: frozenset[str]

    @classmethod
    def of(cls, snapshot: ProjectSnapshot) -> CallGraph:
        """Read one snapshot's call graph; an extraction that carried none yields an empty one."""
        return cls(
            graph=DependencyGraph.from_edges(snapshot.call_edges),
            complexity={node.node: node.complexity for node in snapshot.call_nodes},
            unresolved={node.node: node.unresolved_calls for node in snapshot.call_nodes},
            resolution=dict(snapshot.call_resolution),
            held=snapshot.call_graph_holds,
        )

    def holds(self, node: str) -> bool:
        """Whether the graph covers ``node`` at all, which is what makes a claim about it legal."""
        return node in self.held

    def reach(self, node: str, unparsed: Collection[str]) -> Reach:
        """Everything ``node`` transitively calls, with the confidence that answer carries.

        The walk keeps its own stack rather than recursing, for the reason
        :func:`~scitools_hook.analysis.structure.graph.strongly_connected_components` does: a
        real call graph is deeper than the interpreter's recursion limit long before it is
        large, and a gate must not fail on a big project.
        """
        found = {node}
        pending = [node]
        while pending:
            for target in self.graph.successors_of(pending.pop()):
                if target not in found:
                    found.add(target)
                    pending.append(target)
        reached = tuple(sorted(found))
        return Reach(
            subject=node,
            routines=reached,
            complexity=sum(self.complexity.get(name) or 0.0 for name in reached),
            unmeasured=tuple(name for name in reached if self.complexity.get(name) is None),
            unresolved_calls=sum(self.unresolved.get(name, 0) for name in reached),
            truncated_by=_unparsed_among(reached, unparsed),
        )

    def confidence(self, language: str) -> str:
        """One clause stating how much of ``language``'s call graph resolved (req 7.1).

        A language the extraction reported nothing for says so, rather than saying nothing:
        an absent figure and a perfect one must not read the same.
        """
        found = self.resolution.get(language)
        if found is None or found.bound is None:
            return f"no {language} call-resolution figure was measured for this run"
        return (
            f"{found.unresolved} of {found.total} {language} call sites in this run "
            f"bound to nothing callable ({(1 - found.bound):.0%})"
        )


def evaluate_reachable_complexity(
    after: ProjectSnapshot,
    subjects: Collection[EntityKey],
    limit: Limit | None,
    severity: Severity = "warning",
) -> list[Finding]:
    """Report every judged routine whose transitively reached complexity breaks ``limit``.

    ``subjects`` are the affected routine keys (req 4.2); in whole-project mode they are every
    routine of the project (req 4.8). ``limit`` is the configured rule -- ``None``, or a limit
    with no ``max``, switches the rule off entirely, as a fan direction with no maximum is.
    Only ``max`` is evaluated: a *minimum* reachable complexity is not a maintainability
    statement anyone would make.

    A subject the call graph does not hold yields no finding, because the graph was not asked
    about it. Findings come back in key order.
    """
    if limit is None or limit.max is None:
        return []
    calls = CallGraph.of(after)
    unparsed = after.unparsed_files
    findings = []
    for key in sorted(subjects, key=lambda subject: subject.token):
        if not calls.holds(key.token):
            continue
        reach = calls.reach(key.token, unparsed)
        if reach.complexity > limit.max:
            findings.append(_reach_finding(after, key, reach, calls, limit.max, severity))
    return findings


def find_call_cycles(
    after: ProjectSnapshot,
    subjects: Collection[EntityKey],
    severity: Severity = "warning",
) -> list[Finding]:
    """Report every cycle of two or more routines that a judged routine takes part in.

    A component is reported once, keyed by its members, however many subjects sit on it. A
    self-recursive routine is not a cycle, exactly as a file that references itself is not
    (req 6.1): Understand reports the call, and a routine calling itself says nothing about
    the structure a reviewer cares about.

    Restricting the report to components a subject sits on is also what keeps the answer
    *sound* on a bounded extraction: ``call_edges`` holds the routines forward-reachable from
    the ones the run asked about, and a routine on a cycle through a subject is reachable from
    that subject by definition -- so a subject's own component is complete here, while a
    component further out may not be.
    """
    calls = CallGraph.of(after)
    judged = {key.token for key in subjects if calls.holds(key.token)}
    refs = {key.token: key for key in subjects}
    findings = []
    for component in strongly_connected_components(calls.graph):
        members = judged & component
        if len(component) < 2 or not members:
            continue
        first = sorted(members)[0]
        findings.append(_cycle_finding(after, refs[first], component, calls, severity))
    return findings


def _reach_finding(
    after: ProjectSnapshot,
    key: EntityKey,
    reach: Reach,
    calls: CallGraph,
    limit: float,
    severity: Severity,
) -> Finding:
    """One routine over its reachable-complexity maximum; ``hint`` is the pipeline's job."""
    ref = _ref_of(after, key)
    return Finding(
        kind="structural",
        rule=REACH_RULE,
        metric=COMPLEXITY_METRIC,
        scope="routine",
        entity=ref,
        path=key.path,
        line=None if ref is None else ref.line,
        value=reach.complexity,
        limit=limit,
        limit_source="rule",
        severity=severity,
        blocking=severity == "error",
        message=_reach_message(key, reach, calls, _language_of(after, key), limit),
        details={
            "reached_routines": len(reach.routines),
            "heaviest": _heaviest(reach, calls, DETAIL_CONTRIBUTORS),
            "reaches": [_label(name) for name in reach.routines if name != key.token],
            "unresolved_calls": reach.unresolved_calls,
            "unmeasured_routines": [_label(name) for name in reach.unmeasured],
            "truncated_by_parse_errors": list(reach.truncated_by),
            "call_resolution": calls.confidence(_language_of(after, key)),
        },
    )


def _heaviest(reach: Reach, calls: CallGraph, most: int) -> list[str]:
    """The reached routines carrying the most complexity, heaviest first, as ``"name (45)"``.

    **A total on its own cannot be acted on.** "reaches 323 routines totalling 1214" names the
    problem and not the work; an unordered list of 322 names is no better. Sorting the reach by
    what each member contributes turns the finding into a place to start, and it needs nothing
    the graph does not already carry -- the per-node complexity is what the total was summed
    from. Ties break on the name so two runs over the same code agree.

    A routine with no measured complexity is left out rather than shown as ``0``: it is already
    counted in ``unmeasured_routines``, and a zero here would read as "this one is free".
    """
    scored = [
        (value, _label(name))
        for name in reach.routines
        if (value := calls.complexity.get(name)) is not None
    ]
    scored.sort(key=lambda pair: (-pair[0], pair[1]))
    return [f"{name} ({value:g})" for value, name in scored[:most]]


def _cycle_finding(
    after: ProjectSnapshot,
    key: EntityKey,
    component: frozenset[str],
    calls: CallGraph,
    severity: Severity,
) -> Finding:
    """One call cycle as a finding, named after the judged routine that sits on it."""
    members = sorted(component)
    closing = [_render(edge) for edge in calls.graph.internal_edges(component)]
    ref = _ref_of(after, key)
    return Finding(
        kind="structural",
        rule=CYCLE_RULE,
        scope="routine",
        entity=ref,
        path=key.path,
        line=None if ref is None else ref.line,
        value=len(members),
        limit_source="rule",
        severity=severity,
        blocking=severity == "error",
        message=(
            f"{len(members)} routines call each other in a cycle: "
            f"{', '.join(_label(name) for name in members)}; "
            f"closed by {', '.join(closing)}"
        ),
        details={
            "members": [_label(name) for name in members],
            "closing_calls": closing,
            "call_resolution": calls.confidence(_language_of(after, key)),
        },
    )


def _reach_message(
    key: EntityKey, reach: Reach, calls: CallGraph, language: str, limit: float
) -> str:
    """One line stating the reach, the limit it broke, and why it is a lower bound (req 7.1)."""
    others = len(reach.routines) - 1
    noun = "routine" if others == 1 else "routines"
    blind = (
        f"{reach.unresolved_calls} call sites inside that reach bound to nothing callable"
        if reach.unresolved_calls
        else "no call site inside that reach was left unresolved"
    )
    heaviest = _heaviest(reach, calls, MESSAGE_CONTRIBUTORS)
    worst = f"; heaviest: {', '.join(heaviest)}" if heaviest else ""
    return (
        f"routine {key.longname} reaches {others} {noun} totalling "
        f"{reach.complexity:g} {COMPLEXITY_METRIC}, above the maximum of {limit:g}"
        f"{worst}; a lower bound -- {blind}, and {calls.confidence(language)}"
    )


def _unparsed_among(reached: Iterable[str], unparsed: Collection[str]) -> tuple[str, ...]:
    """The files of the reached routines that failed to parse, sorted and without repeats."""
    if not unparsed:
        return ()
    found = {EntityKey.from_token(name).path for name in reached}
    return tuple(sorted(found & set(unparsed)))


def _render(edge: GraphEdge) -> str:
    """One closing call, in the form the finding shows: ``"a -> b (2 calls)"``."""
    plural = "call" if edge.refs == 1 else "calls"
    return f"{_label(edge.src)} -> {_label(edge.dst)} ({edge.refs} {plural})"


def _label(endpoint: str) -> str:
    """A graph endpoint as it is shown: the routine's qualified name, never a raw token."""
    try:
        return EntityKey.from_token(endpoint).longname
    except ValueError:
        return endpoint


def _ref_of(after: ProjectSnapshot, key: EntityKey) -> EntityRef | None:
    """The entity reference of ``key``, or ``None`` when the snapshot does not hold it.

    A subject reached through the call graph but written in a file the run did not extract
    records for has no reference, which costs the finding its line and nothing else.
    """
    record = after.entities.get(key)
    return None if record is None else record.ref


def _language_of(after: ProjectSnapshot, key: EntityKey) -> str:
    """The language of the judged routine, which decides whose resolution figure applies.

    A snapshot that holds no record for the key falls back to the single language it was
    analysed with, and to ``"unknown"`` when there is more than one -- a wrong language would
    quote a confidence figure that belongs to a different substrate.
    """
    record = after.entities.get(key)
    if record is not None:
        return record.language
    languages: Sequence[str] = after.languages
    return languages[0] if len(languages) == 1 else "unknown"
