"""Evidence-based scope detection: what a repository *declares* about its own directories.

The shipped ``[project] exclude`` list is a guess list, and measured against a real
repository most of it cannot fire at all: the shadow tree is exported from the **git index**,
so anything ``.gitignore`` already removes never enters the analysis. What it misses is the
opposite class -- code that is committed and is nevertheless not the project's own product:
vendored SDKs, generated sources, database migrations and separate sub-projects living inside
one repository.

This module looks for the places a repository has already **said so**, and returns the
statement alongside the verdict:

``gitattributes``
    ``linguist-vendored`` / ``linguist-generated`` in a tracked ``.gitattributes``. The
    strongest signal there is, because it is not a heuristic: the repository owner wrote it
    down. Only *tracked* attribute files are read -- an untracked one is one developer's
    working copy, not a declaration by the repository.
``tool-config``
    A tool naming a directory's role: ``[tool.pytest.ini_options] testpaths`` in a
    ``pyproject.toml``, ``[tool:pytest] testpaths`` in ``tox.ini``/``setup.cfg``, and
    ``[alembic] script_location`` in ``alembic.ini``.
``generated-header``
    A machine-written banner (``@generated``, ``Code generated by ... DO NOT EDIT``) in a
    file's **leading comment block** -- see :func:`_header_comments` for why that qualifier
    is the whole detector.
``subproject``
    A package manifest in a subdirectory: a separate or vendored project inside the tree.
``excluded``
    The paths the *current* configuration already drops. Not a signal about the code at all,
    but the answer to "what is this run not looking at?", which nothing else could give.

Two more detectors answer a different question and are kept apart from the roles for that
reason: which files **Understand cannot read**, and what that costs. PEP 695 is the case that
forced them, because ruff's ``UP040``/``UP046``/``UP047`` write the syntax on purpose and a
project cannot simply stop using it. The two spellings are **not** equally expensive, and the
difference was measured on the licensed Understand 6.5.1204 rather than assumed -- one
database per fixture, each fixture a routine, the construct, and a second routine:

===========================  ============================  ==================================
construct                    parse error reported          the routine *after* it
===========================  ============================  ==================================
``def f[T]`` (``pep695``)    yes, and a cascade to EOF     **gone from the database**
``class C[T]`` (``pep695``)  yes, and a cascade to EOF     **gone from the database**
``async def f[T]``           yes, and a cascade to EOF     **gone from the database**
``def f[**P]``               yes, and a cascade to EOF     **gone from the database**
``type A = int``             yes, one error, that line     present
``type A = int | str``       yes, one error, that line     present
``type A[T] = list[T]``      yes, one error, that line     present
===========================  ============================  ==================================

So a type-parameter list truncates the file and a ``type`` statement does not, while both
raise the parse error that task 11.11 turned into a blocking finding. They are reported under
different signals because the acknowledgement an operator writes for them says different
things about what was measured, and a single reason covering both would be false for one of
them. This repository's own ``pyproject.toml`` lumps ``UP040`` in with ``UP046``/``UP047``;
the measurement above says the alias half of that is over-broad, which is recorded here and
not acted on -- that file belongs to another task.

Either way the file lands in :attr:`Detection.limitations` and is proposed as a **commented**
``[parse] acknowledged`` entry. Uncommenting it is the operator's decision, because it is the
decision to let a file the analyser could not read stop blocking a commit.

**Detection proposes; it never applies.** Nothing here changes a setting. It returns
:class:`Region` values that ``config.template`` renders as configuration lines *with the
evidence in a comment*, for an operator to read and commit. The one thing this module must
never become is a way for the Gate to quietly stop looking at things.

``config`` is the lowest layer in the import matrix, so nothing here may import ``git``: the
tracked file list arrives as an argument.
"""

from __future__ import annotations

import ast
import configparser
import io
import tomllib
from collections.abc import Iterable, Mapping, Sequence
from dataclasses import dataclass, replace
from pathlib import Path
from tokenize import COMMENT, INDENT, NEWLINE, NL, TokenError, generate_tokens
from typing import Final, Literal

from scitools_hook.config.models import ProjectSettings, matching_pattern

Role = Literal["product", "tests", "vendored", "generated", "not-analysed"]
"""What a region of the repository is. ``product`` is the default: nothing said otherwise."""

Signal = Literal[
    "gitattributes",
    "tool-config",
    "generated-header",
    "subproject",
    "excluded",
    "pep695",
    "pep695-alias",
    "fstring-escape",
]
"""Which detector spoke. Every :class:`Evidence` carries one, so a verdict can be traced."""

ROLE_RANK: Final[dict[Role, int]] = {
    "not-analysed": 0,
    "generated": 1,
    "vendored": 2,
    "tests": 3,
    "product": 4,
}
"""Which role wins when several cover one path; lower wins.

``not-analysed`` first because it is a fact about *this run* rather than about the code: a
file the configuration already drops is not measured, whatever else it is.
"""


@dataclass(frozen=True, slots=True)
class Evidence:
    """One thing that was read, and where it was read from.

    ``source`` is the repository-relative file carrying the statement (empty when the signal
    is the configuration itself), and ``detail`` is the text as it stands there. Both are
    verbatim on purpose: a generated configuration line has to be checkable against the file
    it claims to come from.
    """

    signal: Signal
    source: str
    detail: str

    def describe(self) -> str:
        """One line naming the signal, the file and the text, for a comment or a report."""
        where = f" in {self.source}" if self.source else ""
        return f"{self.signal}{where}: {self.detail}"


@dataclass(frozen=True, slots=True)
class Region:
    """One part of the repository, the role something declared for it, and that something."""

    name: str
    role: Role
    pattern: str
    evidence: Evidence
    files: tuple[str, ...] = ()

    @property
    def covered(self) -> int:
        """How many **tracked** files the pattern actually covers.

        Zero is a real and reportable answer, not a bug: ``.dagger/module/.gitattributes`` in
        the repository this was built against declares ``/sdk/** linguist-generated`` while
        ``.dagger/module/.gitignore`` keeps that tree out of the index entirely. The
        declaration is true and worth showing; an exclusion for it would be a dead line.
        """
        return len(self.files)


@dataclass(frozen=True, slots=True)
class Detection:
    """Everything the detectors found in one repository, in a stable order."""

    root: Path
    tracked: tuple[str, ...]
    regions: tuple[Region, ...]
    limitations: tuple[Evidence, ...] = ()
    """Files the analyser cannot read to the end -- a different axis from :class:`Region`."""

    def covering(self, path: str) -> tuple[Region, ...]:
        """Every region whose pattern covers ``path``, strongest role first."""
        found = [region for region in self.regions if matching_pattern([region.pattern], path)]
        return tuple(sorted(found, key=lambda region: (ROLE_RANK[region.role], region.pattern)))

    def role_of(self, path: str) -> Role:
        """The role of ``path``: the strongest one covering it, else ``product``."""
        covering = self.covering(path)
        return covering[0].role if covering else "product"

    def with_role(self, role: Role) -> tuple[Region, ...]:
        """Every region carrying ``role``, in the detection's own order."""
        return tuple(region for region in self.regions if region.role == role)


# --- the entry point ---------------------------------------------------------------


def detect(root: Path, tracked: Sequence[str], project: ProjectSettings | None = None) -> Detection:
    """Classify ``root``'s directories from what its tracked files declare.

    ``tracked`` is the repository-relative POSIX path of every file in the index -- passed in
    rather than looked up, because ``config`` may not import ``git``. ``project`` adds the
    ``not-analysed`` regions: what the configuration in force already drops.
    """
    files = tuple(sorted(tracked))
    found = [
        *_gitattributes_regions(root, files),
        *_tool_config_regions(root, files),
        *_generated_header_regions(root, files),
        *_subproject_regions(files),
        *_excluded_regions(project, files),
    ]
    return Detection(
        root=root,
        tracked=files,
        regions=_finish(found, files),
        limitations=tuple(_parse_limitations(root, files)),
    )


def _finish(found: Iterable[Region], files: Sequence[str]) -> tuple[Region, ...]:
    """Attach the covered files to every region, drop duplicates, and order the result."""
    seen: dict[tuple[str, str, str], Region] = {}
    for region in found:
        key = (region.role, region.pattern, region.evidence.signal)
        if key not in seen:
            covered = tuple(name for name in files if matching_pattern([region.pattern], name))
            seen[key] = replace(region, files=covered)
    return tuple(sorted(seen.values(), key=lambda region: (ROLE_RANK[region.role], region.pattern)))


# --- .gitattributes ----------------------------------------------------------------

GITATTRIBUTES: Final = ".gitattributes"

_LINGUIST_ROLES: Final[dict[str, Role]] = {
    "linguist-vendored": "vendored",
    "linguist-generated": "generated",
}
"""The two attributes GitHub defines for "this is not our code", and what each one means."""


def _gitattributes_regions(root: Path, tracked: Sequence[str]) -> list[Region]:
    """Every ``linguist-vendored``/``linguist-generated`` declaration in the tracked tree."""
    regions: list[Region] = []
    for rel in tracked:
        if _basename(rel) != GITATTRIBUTES:
            continue
        base = _dirname(rel)
        for pattern, attribute, role in _linguist_declarations(_read_text(root / rel)):
            anchored = _anchor(base, pattern)
            detail = f"{pattern} {attribute}"
            evidence = Evidence(signal="gitattributes", source=rel, detail=detail)
            regions.append(
                Region(name=_region_name(anchored), role=role, pattern=anchored, evidence=evidence)
            )
    return regions


def _linguist_declarations(text: str) -> list[tuple[str, str, Role]]:
    """The ``(pattern, attribute, role)`` triples one attributes file sets.

    Written as a parser rather than a search for the word ``linguist``. The line grammar has
    four ways of saying *no* -- ``-attr``, ``!attr``, ``attr=false``, and a ``#`` comment --
    and a grep for the attribute name matches all four just as happily as it matches the one
    way of saying yes. Macro definitions (``[attr]binary ...``) are skipped for the same
    reason: they name the attribute without applying it to any path.
    """
    found: list[tuple[str, str, Role]] = []
    for raw in text.splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or line.startswith("[attr]"):
            continue
        pattern, attributes = _split_attribute_line(line)
        if not pattern:
            continue
        for attribute in attributes:
            name, set_ = _attribute_state(attribute)
            role = _LINGUIST_ROLES.get(name)
            if role is not None and set_:
                found.append((pattern, attribute, role))
    return found


def _split_attribute_line(line: str) -> tuple[str, list[str]]:
    """Split one attributes line into its path pattern and its attribute words.

    git allows the pattern to be double-quoted so it can contain spaces, which is why the
    first field is not simply ``line.split()[0]``.
    """
    if line.startswith('"'):
        closing = line.find('"', 1)
        if closing < 0:
            return "", []
        return line[1:closing], line[closing + 1 :].split()
    fields = line.split()
    return fields[0], fields[1:]


def _attribute_state(attribute: str) -> tuple[str, bool]:
    """One attribute word as ``(name, is_set)``; ``-a``, ``!a`` and ``a=false`` are not set."""
    if attribute.startswith("-"):
        return attribute[1:], False
    if attribute.startswith("!"):
        return attribute[1:], False
    name, separator, value = attribute.partition("=")
    if separator:
        return name, value.lower() not in {"false", "0", ""}
    return name, True


def _anchor(base: str, pattern: str) -> str:
    """Re-express one ``.gitattributes`` pattern relative to the repository root.

    git's rule: a pattern containing a slash is relative to the directory holding the
    attributes file, and one without matches at any depth below it. ``/sdk/**`` inside
    ``.dagger/module/.gitattributes`` therefore means ``.dagger/module/sdk/**`` and not
    ``sdk/**`` -- a distinction that decides whether the generated line an operator reads is
    true.
    """
    core = pattern.rstrip("/")
    if "/" in core.lstrip("/"):
        body = core.lstrip("/")
    elif core.startswith("/"):
        body = core[1:]
    else:
        body = f"**/{core}"
    return f"{base}/{body}" if base else body


# --- tool configuration ------------------------------------------------------------

_PYTEST_INI_SECTIONS: Final = ("tool:pytest", "pytest")
"""Where ``setup.cfg`` and ``tox.ini`` keep pytest's settings, in the order pytest reads them."""


def _tool_config_regions(root: Path, tracked: Sequence[str]) -> list[Region]:
    """Regions a build or migration tool names in its own configuration."""
    regions: list[Region] = []
    for rel in tracked:
        name = _basename(rel)
        if name == "pyproject.toml":
            regions.extend(_pyproject_testpaths(root, rel))
        elif name in {"tox.ini", "setup.cfg"}:
            regions.extend(_ini_testpaths(root, rel))
        elif name == "alembic.ini":
            regions.extend(_alembic_script_location(root, rel))
    return regions


def _pyproject_testpaths(root: Path, rel: str) -> list[Region]:
    """``[tool.pytest.ini_options] testpaths`` -- the project's own word for "these are tests"."""
    table = _toml_table(root / rel, ("tool", "pytest", "ini_options"))
    raw = table.get("testpaths")
    entries = [item for item in raw if isinstance(item, str)] if isinstance(raw, list) else []
    detail = f"[tool.pytest.ini_options] testpaths = {entries}"
    return _testpath_regions(_dirname(rel), rel, entries, detail)


def _ini_testpaths(root: Path, rel: str) -> list[Region]:
    """The same setting where ``setup.cfg`` and ``tox.ini`` keep it."""
    parser = _read_ini(root / rel)
    for section in _PYTEST_INI_SECTIONS:
        if parser.has_option(section, "testpaths"):
            entries = parser.get(section, "testpaths").split()
            detail = f"[{section}] testpaths = {' '.join(entries)}"
            return _testpath_regions(_dirname(rel), rel, entries, detail)
    return []


def _testpath_regions(base: str, rel: str, entries: Sequence[str], detail: str) -> list[Region]:
    """One ``tests`` region per configured test path, relative to the file that named it."""
    evidence = Evidence(signal="tool-config", source=rel, detail=detail)
    regions = []
    for entry in entries:
        name = _join(base, entry.strip("/"))
        if name:
            regions.append(Region(name=name, role="tests", pattern=f"{name}/**", evidence=evidence))
    return regions


def _alembic_script_location(root: Path, rel: str) -> list[Region]:
    """``[alembic] script_location`` -- the directory alembic writes revision scripts into."""
    parser = _read_ini(root / rel)
    if not parser.has_option("alembic", "script_location"):
        return []
    raw = parser.get("alembic", "script_location").strip()
    # alembic interpolates %(here)s to the directory holding the ini file; RawConfigParser
    # hands it back untouched, which is what lets it be resolved here rather than crashing
    # the read on a `format = %(levelname)s` line elsewhere in the same file.
    location = raw.replace("%(here)s", ".").strip("/")
    name = _join(_dirname(rel), _normalise(location))
    if not name:
        return []
    evidence = Evidence(
        signal="tool-config", source=rel, detail=f"[alembic] script_location = {raw}"
    )
    return [Region(name=name, role="generated", pattern=f"{name}/**", evidence=evidence)]


# --- generated-code banners --------------------------------------------------------

_HEADER_BYTES: Final = 4096
"""How much of a file is read looking for a banner; one that is not near the top is not one."""

_DIRECTORY_MINIMUM: Final = 2
"""How many generated files a directory needs before the region is claimed for the directory."""

_HEADER_LINES: Final = 20
"""How many leading comment lines of a non-Python file are considered its header."""

GENERATED_MARKERS: Final[tuple[str, ...]] = (
    "@generated",
    "do not edit",
    "generated by",
    "autogenerated",
    "automatically generated",
)
"""Lower-cased phrases a machine writes above code it wrote. Matched in comments only."""

_COMMENT_STARTS: Final[tuple[str, ...]] = ("//", "#", "--", "/*", "*", "<!--", ";")

_PYTHON_SUFFIXES: Final = frozenset({".py", ".pyi"})

_SOURCE_SUFFIXES: Final = frozenset(
    {
        ".py", ".pyi", ".go", ".js", ".jsx", ".ts", ".tsx", ".java", ".c", ".h", ".cc",
        ".cpp", ".cxx", ".hpp", ".hh", ".cs", ".rs", ".rb", ".php", ".sql", ".kt", ".kts",
        ".swift", ".m", ".mm", ".proto", ".sh", ".scala", ".pl", ".lua",
    }
)  # fmt: skip
"""Extensions worth opening. A banner lives in source, and this bounds an ``init`` run."""


def _generated_header_regions(root: Path, tracked: Sequence[str]) -> list[Region]:
    """Files whose leading comment block says a machine wrote them, grouped where they fill a
    directory.

    A whole directory becomes one region only when it holds **at least two** tracked source
    files and **every one** of them carries a banner; anything less stays one region per
    file. Both halves matter, because a directory pattern claims something about files nobody
    has written yet: ``vendor/gen/**`` would silently swallow the first hand-written file
    added there, and one generated file alone is far too little to claim a directory with.
    """
    marked = [rel for rel in tracked if _is_generated_source(root / rel, rel)]
    if not marked:
        return []
    candidates = _by_directory(rel for rel in tracked if _has_source_suffix(rel))
    grouped = _by_directory(marked)
    whole = {
        folder
        for folder, names in grouped.items()
        if len(names) >= _DIRECTORY_MINIMUM and candidates[folder] == names
    }
    regions = [
        _generated_region(root, folder, f"{folder}/**", min(grouped[folder]))
        for folder in sorted(whole)
    ]
    loose = [rel for rel in marked if _dirname(rel) not in whole]
    return regions + [_generated_region(root, rel, rel, rel) for rel in loose]


def _generated_region(root: Path, name: str, pattern: str, sample: str) -> Region:
    """One ``generated`` region, quoting the banner line of ``sample`` that produced it.

    ``sample`` is carried in rather than searched for again: it is already known to be a
    marked file inside the region, and a second search would be a second chance to disagree
    with the first about which files are generated.
    """
    evidence = Evidence(
        signal="generated-header", source=sample, detail=_marker_line(root / sample)
    )
    return Region(name=name, role="generated", pattern=pattern, evidence=evidence)


def _is_generated_source(path: Path, rel: str) -> bool:
    """Whether ``rel``'s header comments carry a generated-code banner."""
    return bool(_has_source_suffix(rel) and _marker_line(path))


def _marker_line(path: Path) -> str:
    """The first header comment of ``path`` holding a marker, or ``""``."""
    text = _read_text(path, limit=_HEADER_BYTES)
    for comment in _header_comments(path.suffix, text):
        lowered = comment.lower()
        if any(marker in lowered for marker in GENERATED_MARKERS):
            return comment.strip()
    return ""


def _header_comments(suffix: str, text: str) -> list[str]:
    """The leading comment block of a source file -- comments only, and only the leading ones.

    Both qualifiers are the detector. A search of the whole text for ``DO NOT EDIT`` fires on
    the *generator*: in the repository this was measured against,
    ``sdk/codegen/src/codegen/generator.py`` carries the string on line 199, because emitting
    it is that file's job, while the file it writes carries it on line 1. And a search that
    ignores where a string sits fires on prose: this project already recorded a regex over
    source text matching its own docstrings, in the module documenting the thing it searched
    for. Python is therefore tokenised, so a ``COMMENT`` token is told from a ``STRING`` one,
    and the walk stops at the first token that is neither a comment nor a line break -- which
    is what makes a module docstring, and everything after it, invisible here.
    """
    if suffix in _PYTHON_SUFFIXES:
        return _python_header_comments(text)
    return _plain_header_comments(text)


def _python_header_comments(text: str) -> list[str]:
    """Python's leading comment tokens, stopping at the first token that is real code."""
    comments: list[str] = []
    tokens = generate_tokens(io.StringIO(text).readline)
    try:
        for token in tokens:
            if token.type == COMMENT:
                comments.append(token.string)
            elif token.type not in {NL, NEWLINE, INDENT}:
                break
    except (TokenError, SyntaxError, IndentationError, ValueError):
        # A header read stops at _HEADER_BYTES and can cut a string or a bracket in half, so
        # an incomplete tokenisation is the ordinary case, not a failure: the comments already
        # collected are the header, and the tail was never going to be part of it.
        return comments
    return comments


def _plain_header_comments(text: str) -> list[str]:
    """The leading run of comment lines in a language this module does not tokenise."""
    comments: list[str] = []
    for line in text.splitlines()[:_HEADER_LINES]:
        stripped = line.strip()
        if not stripped:
            continue
        if not stripped.startswith(_COMMENT_STARTS):
            break
        comments.append(stripped)
    return comments


# --- files the analyser cannot read to the end -------------------------------------

PARSE_REASONS: Final[dict[str, str]] = {
    "pep695": (
        "Understand 6.5 stops at a PEP 695 type-parameter list (8.0 parses it -- verify with "
        "`check --files` and drop this entry on 8.0): the parse error cascades to "
        "the end of the file and nothing after the declaration is measured."
    ),
    "pep695-alias": (
        "Understand 6.5 rejects a PEP 695 'type' statement (8.0 parses it): the parse error is "
        "reported and "
        "the rest of the file IS still measured. Measured on 6.5.1204."
    ),
    "fstring-escape": (
        "Understand 6.5 cannot parse an f-string whose interpolation is followed by a (8.0 "
        "parses it -- verify and drop on 8.0) "
        "backslash-escaped opening brace; the parse error cascades to the end of the file "
        "and nothing after it is measured. Measured on 6.5.1204."
    ),
}
"""Signal -> the reason a proposed ``[parse]`` acknowledgement carries, spelled once each.

Two entries and not one, because they are not the same statement. Writing the truncating
reason over an alias would tell an operator a file is unmeasured when it is measured, and
writing the alias reason over a type-parameter list would tell them the opposite -- which is
the failure this whole section exists to prevent.
"""

_PEP695_SUFFIXES: Final = frozenset({".py", ".pyi"})


def _parse_limitations(root: Path, tracked: Sequence[str]) -> list[Evidence]:
    """Every tracked Python file holding a construct Understand 6.5 cannot read."""
    found = []
    for rel in sorted(tracked):
        if _suffix(rel) not in _PEP695_SUFFIXES:
            continue
        evidence = _pep695_evidence(rel, _read_text(root / rel))
        if evidence is not None:
            found.append(evidence)
    return found


def _pep695_evidence(rel: str, text: str) -> Evidence | None:
    """The one PEP 695 declaration worth reporting for ``rel``, or ``None``.

    **Parsed, never searched.** A regular expression for ``def f[T](`` matches this project's
    own hint catalogue, which documents the construct in the text of a remediation hint, and
    it matches any prose or test fixture quoting it. An ``ast`` walk cannot: a type-parameter
    list is ``node.type_params`` and a ``type X = ...`` statement is an ``ast.TypeAlias``,
    while the same characters inside a string are an ``ast.Constant`` and have no such field.
    ``ast.parse`` on 3.12+ understands the syntax, which is what makes the detection exact
    rather than approximate.

    A file holding both kinds is reported as the **truncating** one wherever there is one,
    even when an alias comes first: the truncation is what decides how much of the file the
    Gate actually measured, and that is what the acknowledgement has to say.

    A file the running interpreter cannot parse yields nothing. That is the honest answer:
    this detector reports a construct it *found*, and a file it could not read is a different
    problem, which the Gate's own parse-error finding is what reports.
    """
    try:
        tree = ast.parse(text)
    except (SyntaxError, ValueError, RecursionError, MemoryError):
        return None
    declarations = sorted(_type_parameter_nodes(tree), key=_severity_then_line)
    if not declarations:
        return None
    line, construct, signal = declarations[0]
    return Evidence(signal=signal, source=rel, detail=f"line {line}: {construct}")


_TRUNCATING: Final = frozenset({"pep695", "fstring-escape"})
"""Signals whose construct takes the rest of the file with it, measured one at a time.

`pep695-alias` is deliberately absent: a `type X = ...` statement is reported by Understand and
the rest of the file IS still measured, so it must not outrank a construct that truncates.
"""


_Declaration = tuple[int, str, Signal]
"""One PEP 695 construct: where it is, how it reads, and which signal it raises."""


def _severity_then_line(declaration: _Declaration) -> tuple[int, int]:
    """Order declarations so a truncating one outranks an alias, then by line."""
    return (0 if declaration[2] in _TRUNCATING else 1, declaration[0])


def _type_parameter_nodes(tree: ast.AST) -> list[_Declaration]:
    """Every PEP 695 declaration in ``tree``."""
    found: list[_Declaration] = []
    for node in ast.walk(tree):
        if isinstance(node, ast.TypeAlias) and isinstance(node.name, ast.Name):
            found.append((node.lineno, f"type {node.name.id} = ...", "pep695-alias"))
        elif isinstance(node, ast.ClassDef) and node.type_params:
            params = _type_params(node.type_params)
            found.append((node.lineno, f"class {node.name}[{params}]", "pep695"))
        elif isinstance(node, ast.FunctionDef | ast.AsyncFunctionDef) and node.type_params:
            params = _type_params(node.type_params)
            found.append((node.lineno, f"def {node.name}[{params}]", "pep695"))
        elif isinstance(node, ast.JoinedStr) and _escaped_brace_after_interpolation(node):
            found.append((node.lineno, "f-string: interpolation then \\{", "fstring-escape"))
    return found


def _escaped_brace_after_interpolation(node: ast.JoinedStr) -> bool:
    """Whether this f-string holds an interpolation followed by a backslash-escaped ``{``.

    **The order is the whole condition, and so is the direction of the brace.** Measured on
    Understand 6.5.1204, one construct per database:

    ==============================  =========
    ``f"{1}\\{{"``  interpolation then ``\\{``   TRUNCATED
    ``f"{1}\\}}"``  interpolation then ``\\}``   intact
    ``f"\\}}{1}"``  ``\\}`` then interpolation   intact
    ``f"\\{{{1}"``  ``\\{`` then interpolation   intact
    ``f"{1}\\d"``   backslash, no brace          intact
    ==============================  =========

    So a rule reading "a backslash near a brace" would report three files that parse cleanly,
    and one reading "an escaped brace anywhere" would report four. Narrow enough to be true.

    Parsed rather than searched: after parsing, ``{{`` is one literal ``{`` in a ``Constant``,
    so the test is a backslash immediately before a brace in the constant's *value*, not in the
    source text -- which also means a docstring quoting the construct cannot trip it.
    """
    seen_interpolation = False
    for value in node.values:
        if isinstance(value, ast.FormattedValue):
            seen_interpolation = True
        elif seen_interpolation and isinstance(value, ast.Constant):
            if isinstance(value.value, str) and "\\{" in value.value:
                return True
    return False


_TYPE_PARAM_KINDS: Final = (ast.TypeVar, ast.ParamSpec, ast.TypeVarTuple)
"""The three node kinds a type-parameter list can hold; the base class carries no name."""


def _type_params(params: Sequence[ast.type_param]) -> str:
    """The names in a type-parameter list, for the evidence line."""
    return ", ".join(param.name for param in params if isinstance(param, _TYPE_PARAM_KINDS))


# --- sub-projects ------------------------------------------------------------------

MANIFESTS: Final[tuple[str, ...]] = (
    "pyproject.toml",
    "setup.py",
    "package.json",
    "Cargo.toml",
    "go.mod",
    "build.gradle",
    "build.gradle.kts",
    "pom.xml",
    "Gemfile",
    "composer.json",
)
"""Package manifests. One below the root means a separate or vendored project lives there."""


def _subproject_regions(tracked: Sequence[str]) -> list[Region]:
    """Every directory below the root holding a package manifest.

    The role is ``product``: a manifest says "a project starts here", not "this is not ours".
    Deciding which of the two it is takes a second signal, and inventing one would be the
    guessing this module replaces. What the region buys is a *boundary* -- a named region an
    operator can give thresholds of its own, or exclude, on evidence they can see.
    """
    found: dict[str, str] = {}
    for rel in sorted(tracked):
        folder = _dirname(rel)
        if folder and _basename(rel) in MANIFESTS and folder not in found:
            found[folder] = _basename(rel)
    return [
        Region(
            name=folder,
            role="product",
            pattern=f"{folder}/**",
            evidence=Evidence(
                signal="subproject", source=_join(folder, manifest), detail="package manifest"
            ),
        )
        for folder, manifest in found.items()
    ]


# --- what the configuration already drops ------------------------------------------


def _excluded_regions(project: ProjectSettings | None, tracked: Sequence[str]) -> list[Region]:
    """The tracked files the configuration in force keeps out of the analysis.

    Grouped by the pattern that decided, because "which line did this" is the only form of
    the answer an operator can act on. A file no ``include`` pattern selects is reported
    under the include list rather than silently dropped.
    """
    if project is None:
        return []
    patterns: dict[str, str] = {}
    for rel in tracked:
        excluded = matching_pattern(project.exclude, rel)
        if excluded is not None:
            patterns.setdefault(excluded, "exclude")
        elif matching_pattern(project.include, rel) is None:
            patterns.setdefault(rel, "include")
    return [_excluded_region(pattern, key) for pattern, key in patterns.items()]


def _excluded_region(pattern: str, key: str) -> Region:
    """One ``not-analysed`` region: the pattern, and which list it came from."""
    detail = (
        f"[project] exclude = {pattern!r}"
        if key == "exclude"
        else "no [project] include pattern selects this path"
    )
    return Region(
        name=_region_name(pattern),
        role="not-analysed",
        pattern=pattern,
        evidence=Evidence(signal="excluded", source="", detail=detail),
    )


# --- small shared helpers ----------------------------------------------------------


def _basename(rel: str) -> str:
    return rel.rsplit("/", 1)[-1]


def _dirname(rel: str) -> str:
    head, separator, _ = rel.rpartition("/")
    return head if separator else ""


def _join(base: str, name: str) -> str:
    return f"{base}/{name}" if base and name else base or name


def _normalise(location: str) -> str:
    """Drop the ``./`` an interpolated path leaves behind, keeping the rest verbatim."""
    parts = [part for part in location.split("/") if part not in {"", "."}]
    return "/".join(parts)


def _suffix(rel: str) -> str:
    """The file extension of ``rel`` including the dot, or ``""`` when it has none."""
    name = _basename(rel)
    dot = name.rfind(".")
    return name[dot:] if dot > 0 else ""


def _has_source_suffix(rel: str) -> bool:
    return _suffix(rel) in _SOURCE_SUFFIXES


def _by_directory(paths: Iterable[str]) -> dict[str, frozenset[str]]:
    """Group paths by the directory holding them."""
    grouped: dict[str, set[str]] = {}
    for rel in paths:
        grouped.setdefault(_dirname(rel), set()).add(rel)
    return {folder: frozenset(names) for folder, names in grouped.items()}


def _region_name(pattern: str) -> str:
    """The wildcard-free head of a pattern, which is the directory an operator would name."""
    keep: list[str] = []
    for part in pattern.split("/"):
        if any(char in part for char in "*?["):
            break
        keep.append(part)
    return "/".join(keep) or pattern


def _read_text(path: Path, limit: int | None = None) -> str:
    """Read a file for evidence; anything unreadable is simply no evidence.

    Every caller is scanning a repository it did not write, so a missing file (the index
    holds a path the working tree does not), a directory in its place, a permission error and
    a binary blob are all ordinary. None of them is a reason to fail an ``init``, and none of
    them is evidence of anything, so they all answer the same way.
    """
    try:
        with path.open(encoding="utf-8", errors="replace") as handle:
            return handle.read() if limit is None else handle.read(limit)
    except (OSError, ValueError):
        return ""


def _toml_table(path: Path, keys: Sequence[str]) -> Mapping[str, object]:
    """The table at ``keys`` inside a TOML file, or an empty one when it is not there."""
    try:
        data: object = tomllib.loads(_read_text(path))
    except tomllib.TOMLDecodeError:
        return {}
    for key in keys:
        if not isinstance(data, Mapping):
            return {}
        data = data.get(key, {})
    return data if isinstance(data, Mapping) else {}


def _read_ini(path: Path) -> configparser.RawConfigParser:
    """Parse an INI file without interpolation, or answer an empty parser.

    ``RawConfigParser`` rather than ``ConfigParser`` for a measured reason: a stock
    ``alembic.ini`` carries ``format = %(levelname)s ...`` in its logging sections, and the
    interpolating parser raises on it -- so reading ``script_location``, three sections
    higher, would fail on every default alembic file there is.
    """
    parser = configparser.RawConfigParser()
    try:
        parser.read_string(_read_text(path), source=str(path))
    except configparser.Error:
        return configparser.RawConfigParser()
    return parser
